spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@leisurethat_high?TNS_ADMIN=./src/main/resources/wallet
    username: mygoods
    password: OracleOracle123
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.hoiae.mygoods
  configuration:
    map-underscore-to-camel-case: true


