spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@leisurethat_low?TNS_ADMIN=./src/main/resources/wallet
    username: mygoods
    password: OracleOracle123

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: D:\mygoods\
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true


image:
  image-dir: src/main/resources

mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.hoiae.mygoods
  configuration:
    map-underscore-to-camel-case: true
